# code: language=ansible
---
- name: Install packages for directory backups
  apt:
    state: present
    name:
      - logrotate
  tags:
    - backup
- name: Make sure backup directory exists
  file:
    path: "{{ backup_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - backup
- name: Install backup.sh
  template:
    src: templates/directory-backup.sh.j2
    dest: /usr/local/bin/{{ directory.split("/")[-1] }}-directory-backup.sh
    owner: root
    group: root
    mode: 0755
  tags:
    - backup
- name: Install logrotate config
  template:
    src: templates/directory-backup.logrotate.j2
    dest: /etc/logrotate.d/{{ directory.split("/")[-1] }}-directory-backup
    owner: root
    group: root
    mode: 0644
  tags:
    - backup
- name: Install backup cron file
  template:
    src: templates/directory-backup.cron.j2
    dest: /etc/cron.d/{{ directory.split("/")[-1] }}-directory-backup
    owner: root
    group: root
    mode: 0644
  tags:
    - backup
